# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stackedUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 550)
        MainWindow.setMinimumSize(QtCore.QSize(800, 550))
        MainWindow.setMaximumSize(QtCore.QSize(800, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(-1, -1, 801, 551))
        self.stackedWidget.setStyleSheet("#dashBoardPage{background-color: rgb(239, 242, 242); }\n"
                                         "#welcomePage{background-color: rgb(239, 242, 242;) }\n"
                                         "\n"
                                         "")
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setStyleSheet(
            "#loginPage{background-color: qlineargradient( x1:0 y1:0, x2:1 y2:0, stop:0 purple, stop:1 orange);}")
        self.loginPage.setObjectName("loginPage")
        self.userNameInput = QtWidgets.QLineEdit(self.loginPage)
        self.userNameInput.setGeometry(QtCore.QRect(320, 280, 171, 21))
        self.userNameInput.setObjectName("userNameInput")
        self.passwordInput = QtWidgets.QLineEdit(self.loginPage)
        self.passwordInput.setGeometry(QtCore.QRect(320, 370, 171, 21))
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.userNameLabel = QtWidgets.QLabel(self.loginPage)
        self.userNameLabel.setGeometry(QtCore.QRect(320, 250, 171, 20))
        self.userNameLabel.setStyleSheet("color: white;\n"
                                         "")
        self.userNameLabel.setObjectName("userNameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.loginPage)
        self.passwordLabel.setGeometry(QtCore.QRect(320, 340, 171, 20))
        self.passwordLabel.setStyleSheet("color: white;")
        self.passwordLabel.setOpenExternalLinks(False)
        self.passwordLabel.setObjectName("passwordLabel")
        self.loginButton = QtWidgets.QPushButton(self.loginPage)
        self.loginButton.setGeometry(QtCore.QRect(350, 430, 113, 32))
        self.loginButton.setStyleSheet("color: black;")
        self.loginButton.setObjectName("loginButton")
        self.loginTitle = QtWidgets.QFrame(self.loginPage)
        self.loginTitle.setGeometry(QtCore.QRect(260, 120, 291, 80))
        self.loginTitle.setStyleSheet("#loginTitle{background-color: white;\n"
                                      "border: 2px solid black;\n"
                                      "border-radius: 25px;}")
        self.loginTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginTitle.setObjectName("loginTitle")
        self.label = QtWidgets.QLabel(self.loginTitle)
        self.label.setGeometry(QtCore.QRect(9, 10, 271, 61))
        self.label.setStyleSheet("color: black;")
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.loginPage)
        self.welcomePage = QtWidgets.QWidget()
        self.welcomePage.setStyleSheet("")
        self.welcomePage.setObjectName("welcomePage")
        self.sideBar = QtWidgets.QWidget(self.welcomePage)
        self.sideBar.setGeometry(QtCore.QRect(-1, -11, 101, 571))
        self.sideBar.setStyleSheet(
            "#sideBar{background-color: rgb(221, 223, 223); border: 1px solid black;}")
        self.sideBar.setObjectName("sideBar")
        self.menuLabel = QtWidgets.QLabel(self.sideBar)
        self.menuLabel.setGeometry(QtCore.QRect(0, 40, 101, 20))
        self.menuLabel.setStyleSheet("color: black;")
        self.menuLabel.setObjectName("menuLabel")
        self.dashboardButton = QtWidgets.QPushButton(self.sideBar)
        self.dashboardButton.setGeometry(QtCore.QRect(0, 120, 101, 32))
        self.dashboardButton.setStyleSheet("color: black;")
        self.dashboardButton.setObjectName("dashboardButton")
        self.viewBugsButton = QtWidgets.QPushButton(self.sideBar)
        self.viewBugsButton.setGeometry(QtCore.QRect(0, 160, 101, 32))
        self.viewBugsButton.setStyleSheet("color: black;")
        self.viewBugsButton.setObjectName("viewBugsButton")
        self.createBugButton = QtWidgets.QPushButton(self.sideBar)
        self.createBugButton.setGeometry(QtCore.QRect(0, 200, 101, 32))
        self.createBugButton.setStyleSheet("color: black;")
        self.createBugButton.setObjectName("createBugButton")
        self.addUserButton = QtWidgets.QPushButton(self.sideBar)
        self.addUserButton.setGeometry(QtCore.QRect(0, 240, 101, 32))
        self.addUserButton.setStyleSheet("color: black;")
        self.addUserButton.setObjectName("addUserButton")
        self.logoutButton = QtWidgets.QPushButton(self.sideBar)
        self.logoutButton.setGeometry(QtCore.QRect(0, 480, 101, 32))
        self.logoutButton.setStyleSheet("color: black;")
        self.logoutButton.setObjectName("logoutButton")
        self.deleteUserButton = QtWidgets.QPushButton(self.sideBar)
        self.deleteUserButton.setGeometry(QtCore.QRect(0, 280, 101, 32))
        self.deleteUserButton.setStyleSheet("color: black;")
        self.deleteUserButton.setObjectName("deleteUserButton")
        self.label_2 = QtWidgets.QLabel(self.welcomePage)
        self.label_2.setGeometry(QtCore.QRect(119, 25, 661, 511))
        self.label_2.setStyleSheet("#label_2{color: black;}")
        self.label_2.setObjectName("label_2")
        self.stackedWidget.addWidget(self.welcomePage)
        self.dashBoardPage = QtWidgets.QWidget()
        self.dashBoardPage.setObjectName("dashBoardPage")
        self.sideBar_2 = QtWidgets.QWidget(self.dashBoardPage)
        self.sideBar_2.setGeometry(QtCore.QRect(0, -10, 101, 571))
        self.sideBar_2.setStyleSheet(
            "#sideBar_2{background-color: rgb(221, 223, 223); border: 1px solid black;}")
        self.sideBar_2.setObjectName("sideBar_2")
        self.menuLabel_2 = QtWidgets.QLabel(self.sideBar_2)
        self.menuLabel_2.setGeometry(QtCore.QRect(0, 40, 101, 20))
        self.menuLabel_2.setStyleSheet("color: black;")
        self.menuLabel_2.setObjectName("menuLabel_2")
        self.dashboardButton_2 = QtWidgets.QPushButton(self.sideBar_2)
        self.dashboardButton_2.setGeometry(QtCore.QRect(0, 120, 101, 32))
        self.dashboardButton_2.setStyleSheet("color: black;")
        self.dashboardButton_2.setObjectName("dashboardButton_2")
        self.viewBugsButton_2 = QtWidgets.QPushButton(self.sideBar_2)
        self.viewBugsButton_2.setGeometry(QtCore.QRect(0, 160, 101, 32))
        self.viewBugsButton_2.setStyleSheet("color: black;")
        self.viewBugsButton_2.setObjectName("viewBugsButton_2")
        self.createBugButton_2 = QtWidgets.QPushButton(self.sideBar_2)
        self.createBugButton_2.setGeometry(QtCore.QRect(0, 200, 101, 32))
        self.createBugButton_2.setStyleSheet("color: black;")
        self.createBugButton_2.setObjectName("createBugButton_2")
        self.addUserButton_2 = QtWidgets.QPushButton(self.sideBar_2)
        self.addUserButton_2.setGeometry(QtCore.QRect(0, 240, 101, 32))
        self.addUserButton_2.setStyleSheet("color: black;")
        self.addUserButton_2.setObjectName("addUserButton_2")
        self.logoutButton_2 = QtWidgets.QPushButton(self.sideBar_2)
        self.logoutButton_2.setGeometry(QtCore.QRect(0, 480, 101, 32))
        self.logoutButton_2.setStyleSheet("color: black;")
        self.logoutButton_2.setObjectName("logoutButton_2")
        self.deleteUserButton_2 = QtWidgets.QPushButton(self.sideBar_2)
        self.deleteUserButton_2.setGeometry(QtCore.QRect(0, 280, 101, 32))
        self.deleteUserButton_2.setStyleSheet("color: black;")
        self.deleteUserButton_2.setObjectName("deleteUserButton_2")
        self.highCard = QtWidgets.QWidget(self.dashBoardPage)
        self.highCard.setGeometry(QtCore.QRect(150, 40, 271, 191))
        self.highCard.setStyleSheet("#highCard{background-color: rgb(227, 230, 229);\n"
                                    "color: black;\n"
                                    "border: 1px solid balck;\n"
                                    "border-radius: 5px;}")
        self.highCard.setObjectName("highCard")
        self.highLabel = QtWidgets.QLabel(self.highCard)
        self.highLabel.setGeometry(QtCore.QRect(-1, 10, 271, 51))
        self.highLabel.setStyleSheet("color: black;")
        self.highLabel.setObjectName("highLabel")
        self.highCount = QtWidgets.QLabel(self.highCard)
        self.highCount.setGeometry(QtCore.QRect(0, 70, 271, 91))
        self.highCount.setStyleSheet("color: red;")
        self.highCount.setObjectName("highCount")
        self.medCard = QtWidgets.QWidget(self.dashBoardPage)
        self.medCard.setGeometry(QtCore.QRect(480, 40, 271, 191))
        self.medCard.setStyleSheet("#medCard{background-color: rgb(227, 230, 229);\n"
                                   "color: black;\n"
                                   "border: 1px solid balck;\n"
                                   "border-radius: 5px;}")
        self.medCard.setObjectName("medCard")
        self.medLabel = QtWidgets.QLabel(self.medCard)
        self.medLabel.setGeometry(QtCore.QRect(0, 10, 271, 61))
        self.medLabel.setStyleSheet("color: black;\n"
                                    "")
        self.medLabel.setObjectName("medLabel")
        self.medCount = QtWidgets.QLabel(self.medCard)
        self.medCount.setGeometry(QtCore.QRect(0, 70, 271, 91))
        self.medCount.setStyleSheet("color: yellow;")
        self.medCount.setObjectName("medCount")
        self.lowCard = QtWidgets.QWidget(self.dashBoardPage)
        self.lowCard.setGeometry(QtCore.QRect(150, 290, 271, 191))
        self.lowCard.setStyleSheet("#lowCard{background-color: rgb(227, 230, 229);\n"
                                   "color: black;\n"
                                   "border: 1px solid balck;\n"
                                   "border-radius: 5px;\n"
                                   "}")
        self.lowCard.setObjectName("lowCard")
        self.lowLabel = QtWidgets.QLabel(self.lowCard)
        self.lowLabel.setGeometry(QtCore.QRect(0, 10, 271, 61))
        self.lowLabel.setStyleSheet("color: black;")
        self.lowLabel.setObjectName("lowLabel")
        self.lowCount = QtWidgets.QLabel(self.lowCard)
        self.lowCount.setGeometry(QtCore.QRect(0, 70, 271, 91))
        self.lowCount.setStyleSheet("color: green;")
        self.lowCount.setObjectName("lowCount")
        self.completeCard = QtWidgets.QWidget(self.dashBoardPage)
        self.completeCard.setGeometry(QtCore.QRect(480, 290, 271, 191))
        self.completeCard.setStyleSheet("#completeCard{background-color: rgb(227, 230, 229);\n"
                                        "color: black;\n"
                                        "border: 1px solid balck;\n"
                                        "border-radius: 5px;\n"
                                        "}")
        self.completeCard.setObjectName("completeCard")
        self.completeLabel = QtWidgets.QLabel(self.completeCard)
        self.completeLabel.setGeometry(QtCore.QRect(0, 10, 271, 61))
        self.completeLabel.setStyleSheet("color: black;")
        self.completeLabel.setObjectName("completeLabel")
        self.completeCount = QtWidgets.QLabel(self.completeCard)
        self.completeCount.setGeometry(QtCore.QRect(0, 70, 271, 91))
        self.completeCount.setStyleSheet("color: rgb(67, 169, 255);")
        self.completeCount.setObjectName("completeCount")
        self.stackedWidget.addWidget(self.dashBoardPage)
        self.viewBugsPage = QtWidgets.QWidget()
        self.viewBugsPage.setStyleSheet("background-color: black;")
        self.viewBugsPage.setObjectName("viewBugsPage")
        self.stackedWidget.addWidget(self.viewBugsPage)
        self.createBugsPage = QtWidgets.QWidget()
        self.createBugsPage.setObjectName("createBugsPage")
        self.stackedWidget.addWidget(self.createBugsPage)
        self.addUserPage = QtWidgets.QWidget()
        self.addUserPage.setObjectName("addUserPage")
        self.stackedWidget.addWidget(self.addUserPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userNameLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\">USERNAME</p></body></html>"))
        self.passwordLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\">PASSWORD</p><p align=\"center\"><br/></p></body></html>"))
        self.loginButton.setText(_translate("MainWindow", "Log In"))
        self.label.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">BUG TRACKER</span></p></body></html>"))
        self.menuLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">MENU</span></p></body></html>"))
        self.dashboardButton.setText(_translate("MainWindow", "Dashboard"))
        self.viewBugsButton.setText(_translate("MainWindow", "View Bugs"))
        self.createBugButton.setText(_translate("MainWindow", "Create Bug"))
        self.addUserButton.setText(_translate("MainWindow", "Add User"))
        self.logoutButton.setText(_translate("MainWindow", "Log Out"))
        self.deleteUserButton.setText(_translate("MainWindow", "Delete User"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Welcome to Bug Tracker</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Made using Python, MySQL and PyQt5</span></p><p align=\"center\"><br/></p><p align=\"justify\"><span style=\" font-size:14pt;\">This desktop app is a simple bug tracker. It works by storing bug data in a local database and </span></p><p align=\"justify\"><span style=\" font-size:14pt;\">displaying the data to the users. Bugs vary in priority from low to high. Users can mark bugs as </span></p><p align=\"justify\"><span style=\" font-size:14pt;\">complete when they have been fixed. </span></p><p align=\"justify\"><br/></p><p align=\"justify\">The app has 3 different user levels:</p><p align=\"justify\">Admin: No limitation</p><p align=\"justify\">Moderator: Can not create and add users.</p><p align=\"justify\">User: Cannot create bugs or delete them</p><p align=\"justify\"><br/></p><p align=\"justify\">Use the menu on the left to navigate</p><p align=\"center\"><br/></p></body></html>"))
        self.menuLabel_2.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">MENU</span></p></body></html>"))
        self.dashboardButton_2.setText(_translate("MainWindow", "Dashboard"))
        self.viewBugsButton_2.setText(_translate("MainWindow", "View Bugs"))
        self.createBugButton_2.setText(_translate("MainWindow", "Create Bug"))
        self.addUserButton_2.setText(_translate("MainWindow", "Add User"))
        self.logoutButton_2.setText(_translate("MainWindow", "Log Out"))
        self.deleteUserButton_2.setText(
            _translate("MainWindow", "Delete User"))
        self.highLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Total high:</span></p></body></html>"))
        self.highCount.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">1</span></p></body></html>"))
        self.medLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Total medium:</span></p></body></html>"))
        self.medCount.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">4</span></p></body></html>"))
        self.lowLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Total low:</span></p></body></html>"))
        self.lowCount.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">9</span></p></body></html>"))
        self.completeLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Total complete:</span></p></body></html>"))
        self.completeCount.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">8</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
